default:
  before_script:
    - echo "install"
    - pwd
    - whoami
    - npm install

stages:
  - lint
  - deploy


lint:
    stage: lint
    script:
        - echo "run lint"
        - npm run lint

deploy:
    stage: deploy
    script:
        - pkill -f node
        - rm -rf /home/ubuntu/bank-pro
        - cd ~
        - git clone git@gitlab.informatika.org:if3110-2019-02-k02-12/bank-pro.git
        - cd bank-pro
        - npm install 
        - npm run start