default:
  before_script:
    - echo "install"
    - pwd
    - whoami

stages:
  - lint
  - deploy


lint:
    stage: lint
    script:
        - echo "install"
        - npm install
        - echo "run lint"
        - npm run lint

deploy:
    stage: deploy
    script:
        - cd /home/ubuntu/bank-pro
        - git pull origin dev
        - npm install 
        - npm run start